### ISSUE TITLE
How to get the receptive field?

### ISSUE THREAD

**Issue by kirkzZ** [msracver/Deformable-ConvNets#282]
I want to get like this
![image](https://user-images.githubusercontent.com/62935695/114149380-6d498b80-994d-11eb-8386-84f30526f742.png)

**Comment by jsjxyjl** [comment]
I don't know. Was it photoshopped

**Comment by HaozhiQi** [comment]
For example, the coordinate of the top blue dot is (x, y). Then you could get its sampling location (\delta x, \delta y) from the offset feature map. The result (x + \delta x, y + \delta y) is plotted in the middle layer. Because it's 3x3 kernel, there are 9 points plotted in the middle layer.

The process is done again for the bottom (9 x 9) points.

**Comment by HaozhiQi** [comment]
Also see #10 and https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/deform_conv_demo.py

**Comment by kirkzZ** [comment]
The version is too old, is there a new version to implement？

**Comment by kirkzZ** [comment]
> Also see #10 and https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/deform_conv_demo.py

The version is too old, is there a new version to implement
