### ISSUE TITLE
Questions about the deform_psroi_demo.py

### ISSUE THREAD

**Issue by carrierlxk** [msracver/Deformable-ConvNets#48]
In deform_psroi_demo.py, I have two questions  about the details:
1.Why the offset of bounding box(red box) comes from output of **rfcn_cls_offset** layer rather than the output of  **rfcn_bbox_offset** layer? I think the latter is more related to sub bbox location,  or because the  rfcn_**cls**_offset is related to foreground object? 
2.Why set the value of trans_std to 0.1 in function show_dpsroi_offset? Thank you!!

**Comment by chengshuai** [comment]
Hi @carrierlxk 

I have compile the mxnet and copy the folder mxnet/pyhton to external/mxnet,,then run the command python ./rfcn/demo.py ,the error is 
File "./rfcn/demo.py", line 28, in <module>
    from core.tester import im_detect, Predictor
  File "/home/chengshuai/test_sample/Deformable-ConvNets-master/rfcn/core/tester.py", line 15, in <module>
    from module import MutableModule
  File "/home/chengshuai/test_sample/Deformable-ConvNets-master/rfcn/core/module.py", line 19, in <module>
    from mxnet.initializer import Uniform, InitDesc
ImportError: cannot import name InitDesc
I do not know the why the error hanppen and could you tell me the deformal convoluthon network process.  

Thank you!

**Comment by gd-zhang** [comment]
@chengshuai 

rfcn_cls_offset is learned to enhance the classification branch while rfcn_bbox_offset tends to strengthen localization. In this sense, rfcn_cls_offset is likely to focus on objects and rfcn_cls_offset will partly move out of the box to see more context. That's why we visualize rfcn_cls_offset.

Hope this helps.

**Comment by gd-zhang** [comment]
@carrierlxk 

rfcn_cls_offset is learnt to enhance classification branch while rfcn_bbox_offset tends to strengthen localization. In this sense, rfcn_cls_offset is likely to focus on objects and rfcn_bbox_offset will partly move out of the box to see more context. That's why we visualize rfcn_cls_offset.

Hope this helps.
