### ISSUE TITLE
The Result for Faster RCNN

### ISSUE THREAD

**Issue by wlw208dzy** [msracver/Deformable-ConvNets#5]
Thanks for sharing your wonderful job. I noticed that you only submit the train&test scripts for R-FCN. But In your paper, you also conduct other experiments using **Faster RCNN**. Would you mind sharing the result for **Faster RCNN** detector in this MXNET framework?

**Comment by Orpine** [comment]
We don't run Faster RCNN experiments in this framework due to time limit. We will add Faster RCNN script and result in next one or two weeks.

**Comment by wlw208dzy** [comment]
@Orpine Thanks for your answer. Have you already run Faster RCNN experiments in this public framework? Would you please share the training script, and I can test it on my own server.

**Comment by Orpine** [comment]
We encounter some network issue due to the global ransomware attack so our experiments has been interrupted several times. The code is very simple, by now the difference between Faster RCNN and R-FCN is only the symbol definition, so you could reuse R-FCN's code completely, and just need to write your own symbol. We still need time to get COCO's result and ensure our code is correct :).

**Comment by wlw208dzy** [comment]
Thanks again. I am not sure about the hyper parameters (such as the 'num_filter' of the offset Layer). Would you like to share the symbol definition you chose in your experiment? @Orpine

**Comment by Orpine** [comment]
Hi, we have updated faster r-cnn code, please have a look.
