### ISSUE TITLE
Get the error: rpn data not found at ./data/cache/rpn_data/voc_2007_trainval_rpn.pkl

### ISSUE THREAD

**Issue by KeyKy** [msracver/Deformable-ConvNets#55]
When i train faster-rcnn, i get the error:
```
rpn data not found at ./data/cache/rpn_data/voc_2007_trainval_rpn.pkl
```

Where can i get the voc_2007_trainval_rpn.pkl?

**Comment by Oh233** [comment]
Did you directly run train_rcnn .py?

If so, you need to know that this error is because you train a detector without specifying the proposal model. And currently we didn't provide a script to optimize faster rcnn alternatively. 

You may want to look at and modify https://github.com/msracver/Deformable-ConvNets/blob/master/rfcn/train_alternate.py, where we provide how to train R-FCN alternatively.

**Comment by KeyKy** [comment]
yes. Thanks!
